# DataSource configuration
spring:
  datasource:
    url: jdbc:oracle:thin:@10.152.2.161:1521/ORCL
    username: hasallive
    password: hasallive
  server:
    port: 9020
 
    driver-class-name: oracle.jdbc.driver.OracleDriver
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Hibernate configuration
spring:
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  banner:
    location: accelerex.txt

endpoint:
  accountWebservice: "http://10.152.2.161:7001/supernovaws/AccountWebServiceEndPointPort?wsdl"
  customerWebService: "http://10.152.2.161:7001/supernovaws/CustomerWebServiceEndPointPort?wsdl"
  fundTransferWebservice: "http://10.152.2.160:8001/supernovaws/FundsTransferWebServiceEndPointPort?wsdl"

accelerex:
  chanelCode: AGENCY
  channelId: 17

logging:
  level:
    com.neptunesoftware.accelerex.account.AccountController: debug
  pattern:
    console: "%date{ISO8601} %-5level %class{0}:%L - {%X} %msg%n"
