//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.19 at 09:43:48 AM WAT 
//


package data.account;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for creditFacilityDetailsOutputData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="creditFacilityDetailsOutputData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="appStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="applDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="approvedLimitAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="approvedTermCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="approvedTermValue" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="bankOfficerId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="creditRequiredDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="creditTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="creditTypeDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="currencyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="customerNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="expiryDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="overDraftAccountNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="portfolioCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="productCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="productCombinationOption" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="productDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="reasonCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="referenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="repaySourceAccountNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="requestedAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="strApplDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="strApprovedExpiryDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="strApprovedStartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="strCreditReqdDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="strExpiryDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="termCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="termValue" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="unUtilisedAmt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="utilisedAmt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="utilizationMethdCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "creditFacilityDetailsOutputData", namespace = "http://data.creditapp.server.ws.supernova.neptunesoftware.com/", propOrder = {
    "appStatus",
    "applDate",
    "approvedLimitAmount",
    "approvedTermCode",
    "approvedTermValue",
    "bankOfficerId",
    "creditRequiredDate",
    "creditTypeCode",
    "creditTypeDescription",
    "currencyCode",
    "customerId",
    "customerNumber",
    "expiryDate",
    "overDraftAccountNo",
    "portfolioCode",
    "productCode",
    "productCombinationOption",
    "productDesc",
    "reasonCode",
    "referenceNumber",
    "repaySourceAccountNo",
    "requestedAmount",
    "strApplDate",
    "strApprovedExpiryDate",
    "strApprovedStartDate",
    "strCreditReqdDate",
    "strExpiryDate",
    "termCode",
    "termValue",
    "unUtilisedAmt",
    "utilisedAmt",
    "utilizationMethdCode"
})
public class CreditFacilityDetailsOutputData {

    protected String appStatus;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar applDate;
    protected BigDecimal approvedLimitAmount;
    protected String approvedTermCode;
    protected Long approvedTermValue;
    protected Long bankOfficerId;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creditRequiredDate;
    protected String creditTypeCode;
    protected String creditTypeDescription;
    protected String currencyCode;
    protected Long customerId;
    protected String customerNumber;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar expiryDate;
    protected String overDraftAccountNo;
    protected String portfolioCode;
    protected String productCode;
    protected String productCombinationOption;
    protected String productDesc;
    protected String reasonCode;
    protected String referenceNumber;
    protected String repaySourceAccountNo;
    protected BigDecimal requestedAmount;
    protected String strApplDate;
    protected String strApprovedExpiryDate;
    protected String strApprovedStartDate;
    protected String strCreditReqdDate;
    protected String strExpiryDate;
    protected String termCode;
    protected Long termValue;
    protected BigDecimal unUtilisedAmt;
    protected BigDecimal utilisedAmt;
    protected String utilizationMethdCode;

    /**
     * Gets the value of the appStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppStatus() {
        return appStatus;
    }

    /**
     * Sets the value of the appStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppStatus(String value) {
        this.appStatus = value;
    }

    /**
     * Gets the value of the applDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getApplDate() {
        return applDate;
    }

    /**
     * Sets the value of the applDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setApplDate(XMLGregorianCalendar value) {
        this.applDate = value;
    }

    /**
     * Gets the value of the approvedLimitAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getApprovedLimitAmount() {
        return approvedLimitAmount;
    }

    /**
     * Sets the value of the approvedLimitAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setApprovedLimitAmount(BigDecimal value) {
        this.approvedLimitAmount = value;
    }

    /**
     * Gets the value of the approvedTermCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovedTermCode() {
        return approvedTermCode;
    }

    /**
     * Sets the value of the approvedTermCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovedTermCode(String value) {
        this.approvedTermCode = value;
    }

    /**
     * Gets the value of the approvedTermValue property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getApprovedTermValue() {
        return approvedTermValue;
    }

    /**
     * Sets the value of the approvedTermValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setApprovedTermValue(Long value) {
        this.approvedTermValue = value;
    }

    /**
     * Gets the value of the bankOfficerId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBankOfficerId() {
        return bankOfficerId;
    }

    /**
     * Sets the value of the bankOfficerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBankOfficerId(Long value) {
        this.bankOfficerId = value;
    }

    /**
     * Gets the value of the creditRequiredDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreditRequiredDate() {
        return creditRequiredDate;
    }

    /**
     * Sets the value of the creditRequiredDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreditRequiredDate(XMLGregorianCalendar value) {
        this.creditRequiredDate = value;
    }

    /**
     * Gets the value of the creditTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditTypeCode() {
        return creditTypeCode;
    }

    /**
     * Sets the value of the creditTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditTypeCode(String value) {
        this.creditTypeCode = value;
    }

    /**
     * Gets the value of the creditTypeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditTypeDescription() {
        return creditTypeDescription;
    }

    /**
     * Sets the value of the creditTypeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditTypeDescription(String value) {
        this.creditTypeDescription = value;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyCode(String value) {
        this.currencyCode = value;
    }

    /**
     * Gets the value of the customerId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCustomerId(Long value) {
        this.customerId = value;
    }

    /**
     * Gets the value of the customerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerNumber() {
        return customerNumber;
    }

    /**
     * Sets the value of the customerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerNumber(String value) {
        this.customerNumber = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpiryDate(XMLGregorianCalendar value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the overDraftAccountNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOverDraftAccountNo() {
        return overDraftAccountNo;
    }

    /**
     * Sets the value of the overDraftAccountNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOverDraftAccountNo(String value) {
        this.overDraftAccountNo = value;
    }

    /**
     * Gets the value of the portfolioCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortfolioCode() {
        return portfolioCode;
    }

    /**
     * Sets the value of the portfolioCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortfolioCode(String value) {
        this.portfolioCode = value;
    }

    /**
     * Gets the value of the productCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * Sets the value of the productCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCode(String value) {
        this.productCode = value;
    }

    /**
     * Gets the value of the productCombinationOption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCombinationOption() {
        return productCombinationOption;
    }

    /**
     * Sets the value of the productCombinationOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCombinationOption(String value) {
        this.productCombinationOption = value;
    }

    /**
     * Gets the value of the productDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * Sets the value of the productDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductDesc(String value) {
        this.productDesc = value;
    }

    /**
     * Gets the value of the reasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonCode() {
        return reasonCode;
    }

    /**
     * Sets the value of the reasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonCode(String value) {
        this.reasonCode = value;
    }

    /**
     * Gets the value of the referenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceNumber() {
        return referenceNumber;
    }

    /**
     * Sets the value of the referenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceNumber(String value) {
        this.referenceNumber = value;
    }

    /**
     * Gets the value of the repaySourceAccountNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepaySourceAccountNo() {
        return repaySourceAccountNo;
    }

    /**
     * Sets the value of the repaySourceAccountNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepaySourceAccountNo(String value) {
        this.repaySourceAccountNo = value;
    }

    /**
     * Gets the value of the requestedAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRequestedAmount() {
        return requestedAmount;
    }

    /**
     * Sets the value of the requestedAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRequestedAmount(BigDecimal value) {
        this.requestedAmount = value;
    }

    /**
     * Gets the value of the strApplDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrApplDate() {
        return strApplDate;
    }

    /**
     * Sets the value of the strApplDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrApplDate(String value) {
        this.strApplDate = value;
    }

    /**
     * Gets the value of the strApprovedExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrApprovedExpiryDate() {
        return strApprovedExpiryDate;
    }

    /**
     * Sets the value of the strApprovedExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrApprovedExpiryDate(String value) {
        this.strApprovedExpiryDate = value;
    }

    /**
     * Gets the value of the strApprovedStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrApprovedStartDate() {
        return strApprovedStartDate;
    }

    /**
     * Sets the value of the strApprovedStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrApprovedStartDate(String value) {
        this.strApprovedStartDate = value;
    }

    /**
     * Gets the value of the strCreditReqdDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrCreditReqdDate() {
        return strCreditReqdDate;
    }

    /**
     * Sets the value of the strCreditReqdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrCreditReqdDate(String value) {
        this.strCreditReqdDate = value;
    }

    /**
     * Gets the value of the strExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrExpiryDate() {
        return strExpiryDate;
    }

    /**
     * Sets the value of the strExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrExpiryDate(String value) {
        this.strExpiryDate = value;
    }

    /**
     * Gets the value of the termCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermCode() {
        return termCode;
    }

    /**
     * Sets the value of the termCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermCode(String value) {
        this.termCode = value;
    }

    /**
     * Gets the value of the termValue property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTermValue() {
        return termValue;
    }

    /**
     * Sets the value of the termValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTermValue(Long value) {
        this.termValue = value;
    }

    /**
     * Gets the value of the unUtilisedAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUnUtilisedAmt() {
        return unUtilisedAmt;
    }

    /**
     * Sets the value of the unUtilisedAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUnUtilisedAmt(BigDecimal value) {
        this.unUtilisedAmt = value;
    }

    /**
     * Gets the value of the utilisedAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUtilisedAmt() {
        return utilisedAmt;
    }

    /**
     * Sets the value of the utilisedAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUtilisedAmt(BigDecimal value) {
        this.utilisedAmt = value;
    }

    /**
     * Gets the value of the utilizationMethdCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtilizationMethdCode() {
        return utilizationMethdCode;
    }

    /**
     * Sets the value of the utilizationMethdCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtilizationMethdCode(String value) {
        this.utilizationMethdCode = value;
    }

}
