//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.29 at 08:35:41 AM WAT 
//


package com.neptunesoftware.accelerex.data.transaction;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for clearingChequeRequestData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="clearingChequeRequestData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://data.txnprocess.server.ws.supernova.neptunesoftware.com/}XAPIBaseTxnRequestData"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="accountId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="accountNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="chequeNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="clearingTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="destinationBicCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="drcrFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="orginBankCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="orginBicCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="originBusinessUnitId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="payerAccountNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="returnCheque" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="returnChequeField" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="serviceChannel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="trackingNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="txnCcyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="txnCcyId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="txnFloatId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "clearingChequeRequestData", namespace = "http://data.txnprocess.server.ws.supernova.neptunesoftware.com/", propOrder = {
    "accountId",
    "accountNumber",
    "chequeNumber",
    "clearingTypeCode",
    "destinationBicCd",
    "drcrFlag",
    "orginBankCode",
    "orginBicCode",
    "originBusinessUnitId",
    "payerAccountNumber",
    "returnCheque",
    "returnChequeField",
    "serviceChannel",
    "trackingNumber",
    "txnCcyCode",
    "txnCcyId",
    "txnFloatId"
})
public class ClearingChequeRequestData
    extends XAPIBaseTxnRequestData
{

    protected Long accountId;
    protected String accountNumber;
    protected Long chequeNumber;
    protected String clearingTypeCode;
    protected String destinationBicCd;
    protected String drcrFlag;
    protected String orginBankCode;
    protected String orginBicCode;
    protected Long originBusinessUnitId;
    protected String payerAccountNumber;
    protected boolean returnCheque;
    protected boolean returnChequeField;
    protected String serviceChannel;
    protected Long trackingNumber;
    protected String txnCcyCode;
    protected Long txnCcyId;
    protected Long txnFloatId;

    /**
     * Gets the value of the accountId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * Sets the value of the accountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAccountId(Long value) {
        this.accountId = value;
    }

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the chequeNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getChequeNumber() {
        return chequeNumber;
    }

    /**
     * Sets the value of the chequeNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setChequeNumber(Long value) {
        this.chequeNumber = value;
    }

    /**
     * Gets the value of the clearingTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClearingTypeCode() {
        return clearingTypeCode;
    }

    /**
     * Sets the value of the clearingTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClearingTypeCode(String value) {
        this.clearingTypeCode = value;
    }

    /**
     * Gets the value of the destinationBicCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationBicCd() {
        return destinationBicCd;
    }

    /**
     * Sets the value of the destinationBicCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationBicCd(String value) {
        this.destinationBicCd = value;
    }

    /**
     * Gets the value of the drcrFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrcrFlag() {
        return drcrFlag;
    }

    /**
     * Sets the value of the drcrFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrcrFlag(String value) {
        this.drcrFlag = value;
    }

    /**
     * Gets the value of the orginBankCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrginBankCode() {
        return orginBankCode;
    }

    /**
     * Sets the value of the orginBankCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrginBankCode(String value) {
        this.orginBankCode = value;
    }

    /**
     * Gets the value of the orginBicCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrginBicCode() {
        return orginBicCode;
    }

    /**
     * Sets the value of the orginBicCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrginBicCode(String value) {
        this.orginBicCode = value;
    }

    /**
     * Gets the value of the originBusinessUnitId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getOriginBusinessUnitId() {
        return originBusinessUnitId;
    }

    /**
     * Sets the value of the originBusinessUnitId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setOriginBusinessUnitId(Long value) {
        this.originBusinessUnitId = value;
    }

    /**
     * Gets the value of the payerAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerAccountNumber() {
        return payerAccountNumber;
    }

    /**
     * Sets the value of the payerAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerAccountNumber(String value) {
        this.payerAccountNumber = value;
    }

    /**
     * Gets the value of the returnCheque property.
     * 
     */
    public boolean isReturnCheque() {
        return returnCheque;
    }

    /**
     * Sets the value of the returnCheque property.
     * 
     */
    public void setReturnCheque(boolean value) {
        this.returnCheque = value;
    }

    /**
     * Gets the value of the returnChequeField property.
     * 
     */
    public boolean isReturnChequeField() {
        return returnChequeField;
    }

    /**
     * Sets the value of the returnChequeField property.
     * 
     */
    public void setReturnChequeField(boolean value) {
        this.returnChequeField = value;
    }

    /**
     * Gets the value of the serviceChannel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceChannel() {
        return serviceChannel;
    }

    /**
     * Sets the value of the serviceChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceChannel(String value) {
        this.serviceChannel = value;
    }

    /**
     * Gets the value of the trackingNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTrackingNumber() {
        return trackingNumber;
    }

    /**
     * Sets the value of the trackingNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTrackingNumber(Long value) {
        this.trackingNumber = value;
    }

    /**
     * Gets the value of the txnCcyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnCcyCode() {
        return txnCcyCode;
    }

    /**
     * Sets the value of the txnCcyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnCcyCode(String value) {
        this.txnCcyCode = value;
    }

    /**
     * Gets the value of the txnCcyId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTxnCcyId() {
        return txnCcyId;
    }

    /**
     * Sets the value of the txnCcyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTxnCcyId(Long value) {
        this.txnCcyId = value;
    }

    /**
     * Gets the value of the txnFloatId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTxnFloatId() {
        return txnFloatId;
    }

    /**
     * Sets the value of the txnFloatId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTxnFloatId(Long value) {
        this.txnFloatId = value;
    }

}
