//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.29 at 08:35:41 AM WAT 
//


package com.neptunesoftware.accelerex.data.transaction;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for txnProcessOutputData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="txnProcessOutputData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://data.workflow.server.ws.supernova.neptunesoftware.com/}wsBaseWorkFlowData"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="serviceProviderData" type="{http://data.refglobal.server.ws.supernova.neptunesoftware.com/}genericPickListOutputData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="txnCcyOutputArray" type="{http://data.refglobal.server.ws.supernova.neptunesoftware.com/}currencyOutputData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="txnProcessData" type="{http://data.txnprocess.server.ws.supernova.neptunesoftware.com/}txnProcessData" minOccurs="0"/&gt;
 *         &lt;element name="txnTypeOutputArray" type="{http://data.txnprocess.server.ws.supernova.neptunesoftware.com/}txnTypeOutputData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "txnProcessOutputData", namespace = "http://data.txnprocess.server.ws.supernova.neptunesoftware.com/", propOrder = {
    "serviceProviderData",
    "txnCcyOutputArray",
    "txnProcessData",
    "txnTypeOutputArray"
})
public class TxnProcessOutputData
    extends WsBaseWorkFlowData
{

    @XmlElement(nillable = true)
    protected List<GenericPickListOutputData> serviceProviderData;
    @XmlElement(nillable = true)
    protected List<CurrencyOutputData> txnCcyOutputArray;
    protected TxnProcessData txnProcessData;
    @XmlElement(nillable = true)
    protected List<TxnTypeOutputData> txnTypeOutputArray;

    /**
     * Gets the value of the serviceProviderData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serviceProviderData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServiceProviderData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GenericPickListOutputData }
     * 
     * 
     */
    public List<GenericPickListOutputData> getServiceProviderData() {
        if (serviceProviderData == null) {
            serviceProviderData = new ArrayList<GenericPickListOutputData>();
        }
        return this.serviceProviderData;
    }

    /**
     * Gets the value of the txnCcyOutputArray property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the txnCcyOutputArray property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTxnCcyOutputArray().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyOutputData }
     * 
     * 
     */
    public List<CurrencyOutputData> getTxnCcyOutputArray() {
        if (txnCcyOutputArray == null) {
            txnCcyOutputArray = new ArrayList<CurrencyOutputData>();
        }
        return this.txnCcyOutputArray;
    }

    /**
     * Gets the value of the txnProcessData property.
     * 
     * @return
     *     possible object is
     *     {@link TxnProcessData }
     *     
     */
    public TxnProcessData getTxnProcessData() {
        return txnProcessData;
    }

    /**
     * Sets the value of the txnProcessData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TxnProcessData }
     *     
     */
    public void setTxnProcessData(TxnProcessData value) {
        this.txnProcessData = value;
    }

    /**
     * Gets the value of the txnTypeOutputArray property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the txnTypeOutputArray property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTxnTypeOutputArray().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TxnTypeOutputData }
     * 
     * 
     */
    public List<TxnTypeOutputData> getTxnTypeOutputArray() {
        if (txnTypeOutputArray == null) {
            txnTypeOutputArray = new ArrayList<TxnTypeOutputData>();
        }
        return this.txnTypeOutputArray;
    }

}
