//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.29 at 08:35:41 AM WAT 
//


package com.neptunesoftware.accelerex.data.transaction;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for txnProcessRequestData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="txnProcessRequestData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://data.txnprocess.server.ws.supernova.neptunesoftware.com/}XAPIBaseTxnRequestData"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="agentAccountAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="bankLodgement" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="buNm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="chequeNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="customerAccountNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="customerLnAcctNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="depositorName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="errorData" type="{http://common.ws.supernova.neptunesoftware.com/}XAPIErrorData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="loanAcountAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="originBusinessUnitId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="primaryAccountNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="screenCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="taxAccountNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="taxCategory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="transferReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="txnJournalId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="txnProcessData" type="{http://data.txnprocess.server.ws.supernova.neptunesoftware.com/}txnProcessData" minOccurs="0"/&gt;
 *         &lt;element name="txnValidatorResult" type="{http://data.txnprocess.server.ws.supernova.neptunesoftware.com/}webServiceTxnValidatorResult" minOccurs="0"/&gt;
 *         &lt;element name="userOpenDrawerId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="warningErrorData" type="{http://common.ws.supernova.neptunesoftware.com/}XAPIErrorData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "txnProcessRequestData", namespace = "http://data.txnprocess.server.ws.supernova.neptunesoftware.com/", propOrder = {
    "agentAccountAmount",
    "bankLodgement",
    "buNm",
    "chequeNumber",
    "customerAccountNumber",
    "customerLnAcctNumber",
    "depositorName",
    "errorData",
    "loanAcountAmount",
    "originBusinessUnitId",
    "primaryAccountNumber",
    "screenCode",
    "taxAccountNumber",
    "taxCategory",
    "transferReference",
    "txnJournalId",
    "txnProcessData",
    "txnValidatorResult",
    "userOpenDrawerId",
    "warningErrorData"
})
@XmlSeeAlso({
    ServiceVouchersRequestData.class
})
public class TxnProcessRequestData
    extends XAPIBaseTxnRequestData
{

    protected BigDecimal agentAccountAmount;
    protected boolean bankLodgement;
    protected String buNm;
    protected Long chequeNumber;
    protected String customerAccountNumber;
    protected String customerLnAcctNumber;
    protected String depositorName;
    @XmlElement(nillable = true)
    protected List<XAPIErrorData> errorData;
    protected BigDecimal loanAcountAmount;
    protected Long originBusinessUnitId;
    protected String primaryAccountNumber;
    protected String screenCode;
    protected String taxAccountNumber;
    protected String taxCategory;
    protected String transferReference;
    protected Long txnJournalId;
    protected TxnProcessData txnProcessData;
    protected WebServiceTxnValidatorResult txnValidatorResult;
    protected Long userOpenDrawerId;
    @XmlElement(nillable = true)
    protected List<XAPIErrorData> warningErrorData;

    /**
     * Gets the value of the agentAccountAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAgentAccountAmount() {
        return agentAccountAmount;
    }

    /**
     * Sets the value of the agentAccountAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAgentAccountAmount(BigDecimal value) {
        this.agentAccountAmount = value;
    }

    /**
     * Gets the value of the bankLodgement property.
     * 
     */
    public boolean isBankLodgement() {
        return bankLodgement;
    }

    /**
     * Sets the value of the bankLodgement property.
     * 
     */
    public void setBankLodgement(boolean value) {
        this.bankLodgement = value;
    }

    /**
     * Gets the value of the buNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuNm() {
        return buNm;
    }

    /**
     * Sets the value of the buNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuNm(String value) {
        this.buNm = value;
    }

    /**
     * Gets the value of the chequeNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getChequeNumber() {
        return chequeNumber;
    }

    /**
     * Sets the value of the chequeNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setChequeNumber(Long value) {
        this.chequeNumber = value;
    }

    /**
     * Gets the value of the customerAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerAccountNumber() {
        return customerAccountNumber;
    }

    /**
     * Sets the value of the customerAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerAccountNumber(String value) {
        this.customerAccountNumber = value;
    }

    /**
     * Gets the value of the customerLnAcctNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerLnAcctNumber() {
        return customerLnAcctNumber;
    }

    /**
     * Sets the value of the customerLnAcctNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerLnAcctNumber(String value) {
        this.customerLnAcctNumber = value;
    }

    /**
     * Gets the value of the depositorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepositorName() {
        return depositorName;
    }

    /**
     * Sets the value of the depositorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepositorName(String value) {
        this.depositorName = value;
    }

    /**
     * Gets the value of the errorData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the errorData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getErrorData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XAPIErrorData }
     * 
     * 
     */
    public List<XAPIErrorData> getErrorData() {
        if (errorData == null) {
            errorData = new ArrayList<XAPIErrorData>();
        }
        return this.errorData;
    }

    /**
     * Gets the value of the loanAcountAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLoanAcountAmount() {
        return loanAcountAmount;
    }

    /**
     * Sets the value of the loanAcountAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLoanAcountAmount(BigDecimal value) {
        this.loanAcountAmount = value;
    }

    /**
     * Gets the value of the originBusinessUnitId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getOriginBusinessUnitId() {
        return originBusinessUnitId;
    }

    /**
     * Sets the value of the originBusinessUnitId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setOriginBusinessUnitId(Long value) {
        this.originBusinessUnitId = value;
    }

    /**
     * Gets the value of the primaryAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryAccountNumber() {
        return primaryAccountNumber;
    }

    /**
     * Sets the value of the primaryAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryAccountNumber(String value) {
        this.primaryAccountNumber = value;
    }

    /**
     * Gets the value of the screenCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScreenCode() {
        return screenCode;
    }

    /**
     * Sets the value of the screenCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScreenCode(String value) {
        this.screenCode = value;
    }

    /**
     * Gets the value of the taxAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxAccountNumber() {
        return taxAccountNumber;
    }

    /**
     * Sets the value of the taxAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxAccountNumber(String value) {
        this.taxAccountNumber = value;
    }

    /**
     * Gets the value of the taxCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxCategory() {
        return taxCategory;
    }

    /**
     * Sets the value of the taxCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxCategory(String value) {
        this.taxCategory = value;
    }

    /**
     * Gets the value of the transferReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransferReference() {
        return transferReference;
    }

    /**
     * Sets the value of the transferReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransferReference(String value) {
        this.transferReference = value;
    }

    /**
     * Gets the value of the txnJournalId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTxnJournalId() {
        return txnJournalId;
    }

    /**
     * Sets the value of the txnJournalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTxnJournalId(Long value) {
        this.txnJournalId = value;
    }

    /**
     * Gets the value of the txnProcessData property.
     * 
     * @return
     *     possible object is
     *     {@link TxnProcessData }
     *     
     */
    public TxnProcessData getTxnProcessData() {
        return txnProcessData;
    }

    /**
     * Sets the value of the txnProcessData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TxnProcessData }
     *     
     */
    public void setTxnProcessData(TxnProcessData value) {
        this.txnProcessData = value;
    }

    /**
     * Gets the value of the txnValidatorResult property.
     * 
     * @return
     *     possible object is
     *     {@link WebServiceTxnValidatorResult }
     *     
     */
    public WebServiceTxnValidatorResult getTxnValidatorResult() {
        return txnValidatorResult;
    }

    /**
     * Sets the value of the txnValidatorResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebServiceTxnValidatorResult }
     *     
     */
    public void setTxnValidatorResult(WebServiceTxnValidatorResult value) {
        this.txnValidatorResult = value;
    }

    /**
     * Gets the value of the userOpenDrawerId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getUserOpenDrawerId() {
        return userOpenDrawerId;
    }

    /**
     * Sets the value of the userOpenDrawerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setUserOpenDrawerId(Long value) {
        this.userOpenDrawerId = value;
    }

    /**
     * Gets the value of the warningErrorData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the warningErrorData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWarningErrorData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XAPIErrorData }
     * 
     * 
     */
    public List<XAPIErrorData> getWarningErrorData() {
        if (warningErrorData == null) {
            warningErrorData = new ArrayList<XAPIErrorData>();
        }
        return this.warningErrorData;
    }

}
