//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.31 at 02:19:01 PM WAT 
//


package com.neptunesoftware.accelerex.data.customer;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for customerPersonalInformation complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="customerPersonalInformation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="countryOfBirth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="customerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="customerNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="educationQualification" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="employed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ethnicGroup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="fatherName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="maritalStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="motherMaidenName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="noOfDependants" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="profQualification" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="profession" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="religion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="residence" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "customerPersonalInformation", namespace = "http://data.customer.server.ws.supernova.neptunesoftware.com/", propOrder = {
        "countryOfBirth",
        "customerName",
        "customerNumber",
        "educationQualification",
        "employed",
        "ethnicGroup",
        "fatherName",
        "maritalStatus",
        "motherMaidenName",
        "noOfDependants",
        "profQualification",
        "profession",
        "religion",
        "residence",
        "status"
})
public class CustomerPersonalInformation {

    protected String countryOfBirth;
    protected String customerName;
    protected String customerNumber;
    protected String educationQualification;
    protected String employed;
    protected String ethnicGroup;
    protected String fatherName;
    protected String maritalStatus;
    protected String motherMaidenName;
    protected long noOfDependants;
    protected String profQualification;
    protected String profession;
    protected String religion;
    protected String residence;
    protected String status;

    /**
     * Gets the value of the countryOfBirth property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCountryOfBirth() {
        return countryOfBirth;
    }

    /**
     * Sets the value of the countryOfBirth property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCountryOfBirth(String value) {
        this.countryOfBirth = value;
    }

    /**
     * Gets the value of the customerName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the value of the customerName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCustomerName(String value) {
        this.customerName = value;
    }

    /**
     * Gets the value of the customerNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCustomerNumber() {
        return customerNumber;
    }

    /**
     * Sets the value of the customerNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCustomerNumber(String value) {
        this.customerNumber = value;
    }

    /**
     * Gets the value of the educationQualification property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEducationQualification() {
        return educationQualification;
    }

    /**
     * Sets the value of the educationQualification property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEducationQualification(String value) {
        this.educationQualification = value;
    }

    /**
     * Gets the value of the employed property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEmployed() {
        return employed;
    }

    /**
     * Sets the value of the employed property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEmployed(String value) {
        this.employed = value;
    }

    /**
     * Gets the value of the ethnicGroup property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEthnicGroup() {
        return ethnicGroup;
    }

    /**
     * Sets the value of the ethnicGroup property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEthnicGroup(String value) {
        this.ethnicGroup = value;
    }

    /**
     * Gets the value of the fatherName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFatherName() {
        return fatherName;
    }

    /**
     * Sets the value of the fatherName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFatherName(String value) {
        this.fatherName = value;
    }

    /**
     * Gets the value of the maritalStatus property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * Sets the value of the maritalStatus property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMaritalStatus(String value) {
        this.maritalStatus = value;
    }

    /**
     * Gets the value of the motherMaidenName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMotherMaidenName() {
        return motherMaidenName;
    }

    /**
     * Sets the value of the motherMaidenName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMotherMaidenName(String value) {
        this.motherMaidenName = value;
    }

    /**
     * Gets the value of the noOfDependants property.
     */
    public long getNoOfDependants() {
        return noOfDependants;
    }

    /**
     * Sets the value of the noOfDependants property.
     */
    public void setNoOfDependants(long value) {
        this.noOfDependants = value;
    }

    /**
     * Gets the value of the profQualification property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getProfQualification() {
        return profQualification;
    }

    /**
     * Sets the value of the profQualification property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setProfQualification(String value) {
        this.profQualification = value;
    }

    /**
     * Gets the value of the profession property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getProfession() {
        return profession;
    }

    /**
     * Sets the value of the profession property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setProfession(String value) {
        this.profession = value;
    }

    /**
     * Gets the value of the religion property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getReligion() {
        return religion;
    }

    /**
     * Sets the value of the religion property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setReligion(String value) {
        this.religion = value;
    }

    /**
     * Gets the value of the residence property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getResidence() {
        return residence;
    }

    /**
     * Sets the value of the residence property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setResidence(String value) {
        this.residence = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStatus(String value) {
        this.status = value;
    }

}
