//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.31 at 02:19:01 PM WAT 
//


package com.neptunesoftware.accelerex.data.customer;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;

import java.math.BigDecimal;


/**
 * <p>Java class for groupInformationResponseData complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="groupInformationResponseData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="businessUnitId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="customerNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="groupAcctId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="groupCentreId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="groupName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="groupSize" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="maxGroupSize" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="meetingFrequecyCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="meetingFrequencyValue" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="meetingLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="minGroupSize" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="savingsAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="savingsCurrencyId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="syncDisbursementMeeting" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="syncRepaymentMeeting" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "groupInformationResponseData", namespace = "http://data.customer.server.ws.supernova.neptunesoftware.com/", propOrder = {
        "businessUnitId",
        "customerNo",
        "groupAcctId",
        "groupCentreId",
        "groupName",
        "groupSize",
        "maxGroupSize",
        "meetingFrequecyCd",
        "meetingFrequencyValue",
        "meetingLocation",
        "minGroupSize",
        "savingsAmount",
        "savingsCurrencyId",
        "syncDisbursementMeeting",
        "syncRepaymentMeeting"
})
public class GroupInformationResponseData {

    protected Long businessUnitId;
    protected String customerNo;
    protected Long groupAcctId;
    protected Long groupCentreId;
    protected String groupName;
    protected Long groupSize;
    protected Long maxGroupSize;
    protected String meetingFrequecyCd;
    protected Long meetingFrequencyValue;
    protected String meetingLocation;
    protected Long minGroupSize;
    protected BigDecimal savingsAmount;
    protected Long savingsCurrencyId;
    protected String syncDisbursementMeeting;
    protected String syncRepaymentMeeting;

    /**
     * Gets the value of the businessUnitId property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getBusinessUnitId() {
        return businessUnitId;
    }

    /**
     * Sets the value of the businessUnitId property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setBusinessUnitId(Long value) {
        this.businessUnitId = value;
    }

    /**
     * Gets the value of the customerNo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCustomerNo() {
        return customerNo;
    }

    /**
     * Sets the value of the customerNo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCustomerNo(String value) {
        this.customerNo = value;
    }

    /**
     * Gets the value of the groupAcctId property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getGroupAcctId() {
        return groupAcctId;
    }

    /**
     * Sets the value of the groupAcctId property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setGroupAcctId(Long value) {
        this.groupAcctId = value;
    }

    /**
     * Gets the value of the groupCentreId property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getGroupCentreId() {
        return groupCentreId;
    }

    /**
     * Sets the value of the groupCentreId property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setGroupCentreId(Long value) {
        this.groupCentreId = value;
    }

    /**
     * Gets the value of the groupName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * Sets the value of the groupName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setGroupName(String value) {
        this.groupName = value;
    }

    /**
     * Gets the value of the groupSize property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getGroupSize() {
        return groupSize;
    }

    /**
     * Sets the value of the groupSize property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setGroupSize(Long value) {
        this.groupSize = value;
    }

    /**
     * Gets the value of the maxGroupSize property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getMaxGroupSize() {
        return maxGroupSize;
    }

    /**
     * Sets the value of the maxGroupSize property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setMaxGroupSize(Long value) {
        this.maxGroupSize = value;
    }

    /**
     * Gets the value of the meetingFrequecyCd property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMeetingFrequecyCd() {
        return meetingFrequecyCd;
    }

    /**
     * Sets the value of the meetingFrequecyCd property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMeetingFrequecyCd(String value) {
        this.meetingFrequecyCd = value;
    }

    /**
     * Gets the value of the meetingFrequencyValue property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getMeetingFrequencyValue() {
        return meetingFrequencyValue;
    }

    /**
     * Sets the value of the meetingFrequencyValue property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setMeetingFrequencyValue(Long value) {
        this.meetingFrequencyValue = value;
    }

    /**
     * Gets the value of the meetingLocation property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMeetingLocation() {
        return meetingLocation;
    }

    /**
     * Sets the value of the meetingLocation property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMeetingLocation(String value) {
        this.meetingLocation = value;
    }

    /**
     * Gets the value of the minGroupSize property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getMinGroupSize() {
        return minGroupSize;
    }

    /**
     * Sets the value of the minGroupSize property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setMinGroupSize(Long value) {
        this.minGroupSize = value;
    }

    /**
     * Gets the value of the savingsAmount property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getSavingsAmount() {
        return savingsAmount;
    }

    /**
     * Sets the value of the savingsAmount property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setSavingsAmount(BigDecimal value) {
        this.savingsAmount = value;
    }

    /**
     * Gets the value of the savingsCurrencyId property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getSavingsCurrencyId() {
        return savingsCurrencyId;
    }

    /**
     * Sets the value of the savingsCurrencyId property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setSavingsCurrencyId(Long value) {
        this.savingsCurrencyId = value;
    }

    /**
     * Gets the value of the syncDisbursementMeeting property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSyncDisbursementMeeting() {
        return syncDisbursementMeeting;
    }

    /**
     * Sets the value of the syncDisbursementMeeting property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSyncDisbursementMeeting(String value) {
        this.syncDisbursementMeeting = value;
    }

    /**
     * Gets the value of the syncRepaymentMeeting property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSyncRepaymentMeeting() {
        return syncRepaymentMeeting;
    }

    /**
     * Sets the value of the syncRepaymentMeeting property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSyncRepaymentMeeting(String value) {
        this.syncRepaymentMeeting = value;
    }

}
